blank_issues_enabled: true
contact_links:
  - name: Question or Support
    url: https://github.com/pchynoweth/svelte-assets-preprocessor/discussions
    about: Ask questions or get help from the community
  - name: Documentation
    url: https://github.com/pchynoweth/svelte-assets-preprocessor#readme
    about: Read the documentation
